/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User
    listings: Listing
    categories: Category
    types: Type
    offerings: Offering
    amenities: Amenity
    media: Media
    highlights: Highlight
    "landlord-reviews": LandlordReview
    "listing-reviews": ListingReview
  }
  globals: {}
}
export interface User {
  id: string
  firstName?: string
  lastName?: string
  favourites?: {
    listing?: string | Listing
    id?: string
  }[]
  roles?: ("admin" | "user")[]
  updatedAt: string
  createdAt: string
  email?: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  loginAttempts?: number
  lockUntil?: string
  password?: string
}
export interface Listing {
  id: string
  title: string
  description: string
  category: string | Category
  offerings: string[] | Offering[]
  highlights: string[] | Highlight[]
  author: string | User
  amenities: string[] | Amenity[]
  type: string | Type
  province: string
  street: string
  unitNumber: string
  suburb: string
  city: string
  postalCode: string
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number]
  featureImage?: string | Media
  price: number
  images: {
    image: string | Media
    id?: string
  }[]
  roomCount: number
  bedCount: number
  bathroomCount: number
  guestCount: number
  updatedAt: string
  createdAt: string
  _status?: "draft" | "published"
}
export interface Category {
  id: string
  label: string
  updatedAt: string
  createdAt: string
}
export interface Offering {
  id: string
  label: string
  updatedAt: string
  createdAt: string
}
export interface Highlight {
  id: string
  label: string
  icon: string
  updatedAt: string
  createdAt: string
}
export interface Amenity {
  id: string
  label: string
  updatedAt: string
  createdAt: string
}
export interface Type {
  id: string
  label: string
  description: string
  icon: string
  updatedAt: string
  createdAt: string
}
export interface Media {
  id: string
  alt?: string
  updatedAt: string
  createdAt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  sizes?: {
    thumbnail?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
    card?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
    tablet?: {
      url?: string
      width?: number
      height?: number
      mimeType?: string
      filesize?: number
      filename?: string
    }
  }
}
export interface LandlordReview {
  id: string
  author: string | User
  review: string
  rating: number
  landlord: string | User
  updatedAt: string
  createdAt: string
}
export interface ListingReview {
  id: string
  author: string | User
  review: string
  rating: number
  listing: string | Listing
  updatedAt: string
  createdAt: string
}
