export const spaceCreationSteps = [
  {
    keys: "title",
    path: "/title",
    name: "Title",
    label: "Add a title to your space",
    nextPath: "/type",
  },
  {
    keys: "type",
    path: "/type",
    name: "Type",
    label: "What type of space do you have?",
    nextPath: "/category",
  },
  {
    keys: "category",
    path: "/category",
    name: "Category",
    label: "What category is your space?",
    nextPath: "/address",
  },
  {
    keys: ["province", "street", "unitNumber", "city", "suburb", "postalCode"],
    path: "/address",
    name: "Address",
    label: "Where is your space?",
    nextPath: "/features",
  },
  {
    keys: ["rooms", "desks", "bathrooms"],
    path: "/features",
    name: "Features",
    label: "What does your space feature?",
    nextPath: "/offerings",
  },
  {
    keys: "offerings",
    path: "/offerings",
    name: "Offerings",
    label: "What does your space of to offer?",
    nextPath: "/images",
  },
  {
    keys: "images",
    path: "/images",
    name: "Images",
    label: "What does your space look like?",
    nextPath: "/amenities",
  },
  {
    keys: "amenities",
    path: "/amenities",
    name: "Amenities",
    label: "What amenities does your space have?",
    nextPath: "/highlights",
  },
  {
    keys: "highlights",
    path: "/highlights",
    name: "Highlights",
    label: "What makes your space stand out?",
    nextPath: "/price",
  },
  {
    keys: "price",
    path: "/price",
    name: "Price",
    label: "How much does your space cost?",
    nextPath: null,
  },
]
